name: Run Java In GCP VM

on:
  push:

jobs:

  run-java:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Run Java In VM
        run: |
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
            cd /home/kotta &&
            javac Hello.java &&
            java Hello
          "
