name: tested
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: "select the project"
        required: true
        default: "DEV"
        type: choice
        options:
          - DEV
          - QA
          - PROD
env:
  APP_NAME: Value

jobs:
  built-test:
    runs-on: ubuntu-latest
    steps:
      - name: fetching from params
        run: echo "fetvhing env is ${{github.event.inputs.environment}}"
      - name: feching from envi
        run: echo "fetched value is $APP_NAME"
      - name: Authentication
        env:
          GCP_TOKEN: ${{secrets.GCP_TOKEN}}
        run: echo "Authentication successful"
      - name: cleanup
        if: always()
        run: echo "Workflow completed"
            
        
