name: Test
on:
  push:
  workflow_dispatch:
env:
  APP_NAME: Fytuin
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Building application
        run: echo "building $APP_NAME"
      - name: Tesing application
        run: echo "Testing done for $APP_NAME"
      - name: success message
        if: success()
        run: echo "Pipeline executed successfully!"

      - name: Failure Message
        if: failure()
        run: echo "Pipeline failed!"
