name: Second Pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome message
        run: echo "Hello from github"
      - name: print success message
        run: echo "Pipeline executed successfully"
