name: Second Workflow

on: pull_request
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Print Welcome Message
        run: echo "Hello from GitHub Actions"

      - name: Print Success Message
        run: echo "Workflow executed successfully"
